apiVersion: v1 
kind: Pod  
metadata: 
  name: myapp-pod
  namespace: test
  labels: 
    app: myapp         
spec:
  containers: 
    - name: myapp
      image: nginx
      ports:
        - containerPort: 80