name: configure app server

on:
    workflow_dispatch:

jobs:
    provision-three-tier:
        runs-on: amazon-linux
        env:
            ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
            DEPLOYER_PASSWORD: ${{ secrets.DEPLOYER_PASSWORD }}
            TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
    
        steps:
            - name: checkout
              uses: actions/checkout@v3
            
            - name: configure tomcat
              run: ansible-playbook app_server_config.yml -i hosts
