name: build packer image

on:
    push:
      branches:
        - main
      paths:
        - image-builder/*

    workflow_dispatch:

jobs:
    build-image:
        runs-on: ubuntu-latest

        env:
            PKR_VAR_region: us-east-1
            AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
        
    
        steps:
            - name: Checkout
              uses: actions/checkout@v3
    
            - name: setup packer
              id: setup
              uses: hashicorp/setup-packer@main
    
            - name: initialize packer
              run: "packer init image-builder"
            
            - name: fmt & validate packer
              run: "packer validate ./image-builder/"
            
            - name: build packer image
              run: "packer build ./image-builder/"

