name: checkout private repo
on:
  workflow_dispatch:

jobs:
  checks:
     name: checkout private repo
     runs-on: ubuntu-latest
     steps:
       - name: checkout repo
         uses: actions/checkout@v3
         with:
           repository: Gauravlwplabs/terraform_multibranch
           token: ${{ secrets.gh_app_token }}
