name: provision three tier architecture using terraform

on:
    workflow_dispatch:

jobs:
    provision-three-tier:
        runs-on: ubuntu-latest
    
        steps:
            - name: checkout
              uses: actions/checkout@v3
            
            - name: setup terarform
              uses: hashicorp/setup-terraform@v2
            
            - name: terraform initialize
              run: terraform init
            
            - name: terraform format and validate
              run: |
                terraform fmt
                terraform validate
            
            - name: terraform plan
              run: terraform plan -input=false
            
            - name: terraform apply
              run: terraform apply --auto-approve
